export enum Pages {
    Main = '',
    Welcome = 'welcome',
    Auth = 'auth',
    Game = 'game',
    Map = 'map',
    Presentation = 'presentation',
    ProductPresentation = 'product-presentation',
    Register = 'register',
    Rules = 'rules',
    Knowledge = 'knowledge',
    Profile = 'profile',
    Organizator = 'organizator',
    OrganizatorMark = 'organizator-mark',
    RegisterSuccess = 'register-success',
    OrgRegisterSuccess = 'org-register-success',
}
